version: "3"
services:
    web:
        container_name: go_server
        build: .
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/go/src/speed_reader

